---
title: "2-State_MCMC_Results_Plots"
author: "Rebecca Perez"
date: "2024-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/FEB_ST131/Updated ST131 Code")
library(dplyr)
library(rstan)
library(forester)
library(ggplot2)
pars <- c("beta12", "beta21")
```

##Load stan results for overall analysis 
```{r}
load("TS2.indiv.model1.Rdata")

beta21overall <- unlist(rstan::extract(TS2.indiv.model1, pars = 'beta21'))

beta12overall <- unlist(rstan::extract(TS2.indiv.model1, pars = 'beta12'))

##check model fit diagnostics 
traceplot(TS2.indiv.model1, pars = pars)
check_hmc_diagnostics(TS2.indiv.model1) 
stan_dens(TS2.indiv.model1, pars = pars)

##Carriage 

beta21overall <- exp(beta21overall)
carriageresults <- 1/beta21overall
carriagemean <- median(carriageresults)
carriagequantile <- quantile(carriageresults, prob=c(0.05,0.95))

##Acquisition rate:


overallacq <- exp(beta12overall)
acqmean <- median(overallacq) 
acqquantile <- quantile(overallacq, prob = c(0.05, 0.95))

```

##Load stan results for persistent carriers 
```{r}
load('PERS2.indiv.model1.Rdata')

beta21PERS <- unlist(rstan::extract(PERS2.indiv.model1, pars = 'beta21'))

beta12PERS <- unlist(rstan::extract(PERS2.indiv.model1, pars = 'beta12'))

##check model fit diagnostics 
traceplot(PERS2.indiv.model1, pars = pars)
check_hmc_diagnostics(PERS2.indiv.model1) 
stan_dens(PERS2.indiv.model1, pars = pars)

##Carriage 

beta21PERS <- exp(beta21PERS)
PERScarriageresults <- 1/beta21PERS
PERScarriagemean <- median(PERScarriageresults)
PERScarriagequantile <- quantile(PERScarriageresults, prob=c(0.05,0.95))

##Acquisition rate:


PERSacq <- exp(beta12PERS)
PERSacqmean <- median(PERSacq)
PERSacqquantile <- quantile(PERSacq, prob = c(0.05, 0.95))

```

##Load stan results for coresidents of persistent carriers

```{r}

load('CORES2.indiv.model1.Rdata')

beta21CORES <- unlist(rstan::extract(CORES2.indiv.model1, pars = 'beta21'))

beta12CORES <- unlist(rstan::extract(CORES2.indiv.model1, pars = 'beta12'))

##check model fit diagnostics 
traceplot(CORES2.indiv.model1, pars = pars)
check_hmc_diagnostics(CORES2.indiv.model1)
stan_dens(CORES2.indiv.model1, pars = pars)

####Carriage 

beta21CORES <- exp(beta21CORES)
COREScarriageresults <- 1/beta21CORES
COREScarriagemean <- mean(COREScarriageresults)
COREScarriagequantile <- quantile(COREScarriageresults, prob=c(0.05,0.95))


##Acquisition rate:
CORESacq <- exp(beta12CORES)
CORESacqmean <- median(CORESacq) 
CORESacqquantile <- quantile(CORESacq, prob = c(0.05, 0.95))

```

##Load stan results for all others 

```{r}
load("NONCORES2.indiv.model1.Rdata")

beta21NONCORES <- unlist(rstan::extract(NONCORES2.indiv.model1, pars = 'beta21'))

beta12NONCORES <- unlist(rstan::extract(NONCORES2.indiv.model1, pars = 'beta12'))

##check model fit diagnostics 
traceplot(NONCORES2.indiv.model1, pars = pars)
check_hmc_diagnostics(NONCORES2.indiv.model1)  
stan_dens(NONCORES2.indiv.model1, pars = pars)

##Carriage 
beta21NONCORES <- exp(beta21NONCORES)
NONCOREScarriageresults <- 1/beta21NONCORES
NONCOREScarriagemean <- mean(NONCOREScarriageresults)
NONCOREScarriagequantile <- quantile(NONCOREScarriageresults, prob=c(0.05,0.95))

##Acquisition rate
NONCORESacq <- exp(beta12NONCORES)
NONCORESacqmean <- median(NONCORESacq) 
NONCORESacqquantile <- quantile(NONCORESacq, prob = c(0.05, 0.95))

```

##Plot probability of acquisition 
```{r}
CrIAcq<- matrix(nrow = 3, ncol = 4, data = NA)
CrIAcq[1:3,1] <- c("Persistent carrier", "Coresident of persistent carrier", "All others")
CrIAcq[1,2] <- median(PERSacq)
interval80 <- quantile(PERSacq, prob = c(.1, .9))
CrIAcq[1,3] <- interval80[1]
CrIAcq[1,4] <- interval80[2]

CrIAcq[2,2] <- median(CORESacq)
interval80 <- quantile(CORESacq, prob = c(.1, .9))
CrIAcq[2,3] <- interval80[1]
CrIAcq[2,4] <- interval80[2]

CrIAcq[3,2] <- median(NONCORESacq)
interval80 <- quantile(NONCORESacq, prob = c(.1, .9))
CrIAcq[3,3] <- interval80[1]
CrIAcq[3,4] <- interval80[2]

colnames(CrIAcq) <- c("Group", "Median", "Lower", "Upper")

CrIAcq <- as.data.frame(CrIAcq)

CrIAcq[,2] <- as.numeric(CrIAcq[,2])
CrIAcq[,3] <- as.numeric(CrIAcq[,3])
CrIAcq[,4] <- as.numeric(CrIAcq[,4])

CrIAcq[,2] <- round(CrIAcq[,2], digits = 3)
CrIAcq[,3] <- round(CrIAcq[,3], digits = 3)
CrIAcq[,4] <- round(CrIAcq[,4], digits = 3)


forester(CrIAcq[,c(2,1)], CrIAcq[,2], CrIAcq[,3], CrIAcq[,4], ci_sep = " - ", null_line_at = 0.0, estimate_precision = 3, estimate_col_name = "Daily Probability of Acquisition [80% CrI]", file_path = "/Users/lynnperez/Downloads/V3_MCMC_Acquisition_Forest_Plot.png", nudge_width = -0.5, font_family = "Arial", x_scale_linear=TRUE, xbreaks = seq(0, 0.1, length.out = 5), stripe_colour = "white", point_sizes = 2)

```


##Plot duration of carriage 
```{r}

plot_2_means <- as.data.frame(matrix(data = NA, nrow = 3, ncol = 4))

colnames(plot_2_means) <- c("median", "lower", "upper", "Epidemiological Subgroup")

plot_2_means[1,1] <- PERScarriagemean
plot_2_means[1,2] <- PERScarriagequantile[1]
plot_2_means[1,3] <- PERScarriagequantile[2]
plot_2_means[1,4] <- "Persistent carrier"


plot_2_means[2,1] <- COREScarriagemean
plot_2_means[2,2] <- COREScarriagequantile[1]
plot_2_means[2,3] <- COREScarriagequantile[2]
plot_2_means[2,4] <- "Coresident of persistent carrier"

plot_2_means[3,1] <- NONCOREScarriagemean
plot_2_means[3,2] <- NONCOREScarriagequantile[1]
plot_2_means[3,3] <- NONCOREScarriagequantile[2]
plot_2_means[3,4] <- "All others"


plot_2_means[,1] <- as.numeric(plot_2_means[,1])
plot_2_means[,2] <- as.numeric(plot_2_means[,2])
plot_2_means[,3] <- as.numeric(plot_2_means[,3])

plot_2_means[,1] <- round(plot_2_means[,1], digits = 3)
plot_2_means[,2] <- round(plot_2_means[,2], digits = 3)
plot_2_means[,3] <- round(plot_2_means[,3], digits = 3)



forester(plot_2_means[,c(1,4)], plot_2_means[,1], plot_2_means[,2], plot_2_means[,3], ci_sep = " - ", null_line_at = 0, estimate_col_name = "Carriage Duration [80% CrI]", file_path = "/Users/lynnperez/Downloads/V3_MCMC_Carriage_Forest_Plot.png", nudge_width = -0.5, font_family = "Arial", x_scale_linear=FALSE, stripe_colour = "white", point_sizes = 2)

```

